In [1]:
%load_ext autoreload


## Nombre: Luis Lema
## Fecha: 13/01/2025
## Repositorio: https://github.com/LuisALema/Metodos_Numericos_2025B/tree/main/Talleres/Taller%202B

## Determinante

In [7]:
# ============================================================
# CELDA 1 (una sola vez): IMPORTS + FUNCIONES PRINCIPALES
# ============================================================
%autoreload 2
import numpy as np
from src import (
    descomposicion_LU,
    resolver_LU,
)

def inversa_por_LU(A: list[list[float]]) -> np.ndarray:
    A_np = np.array(A, dtype=float)
    n = A_np.shape[0]
    assert A_np.shape[0] == A_np.shape[1], "A debe ser cuadrada."

    L, U = descomposicion_LU(A_np)

    invA = np.zeros((n, n), dtype=float)
    for i in range(n):
        e = np.zeros((n, 1), dtype=float)
        e[i, 0] = 1.0
        x = resolver_LU(L, U, e)
        invA[:, i] = x.flatten()

    return invA


def procesar_matriz(A: list[list[float]], b_list: list[list[float]], nombre: str):
    A_np = np.array(A, dtype=float)
    n = A_np.shape[0]

    print(f"\n==================== {nombre} ====================")

    # Inversa
    invA = inversa_por_LU(A)
    print(f"\nInversa de {nombre}:\n{invA}")

    # LU
    L, U = descomposicion_LU(A_np)
    print(f"\nL de {nombre}:\n{L}")
    print(f"\nU de {nombre}:\n{U}")

    # Soluciones Ax=b
    for i, b in enumerate(b_list, start=1):
        b_np = np.array(b, dtype=float).reshape(-1, 1)

        if b_np.shape[0] != n:
            print(f"\n(b{i}) NO se puede: b tiene {b_np.shape[0]} filas y {nombre} es {n}x{n}")
            continue

        x = resolver_LU(L, U, b_np)
        print(f"\nSolución para b{i} (de {nombre}):\n{b_np}\n=> x =\n{x}")


# Ejercicio 1

In [ ]:

A1 = [
    [1, 3, 4],
    [2, 1, 3],
    [4, 2, 1],
]

b1_3 = [1, 2, 4]
b2_3 = [3, -5, 2]
b3_3 = [7, 8, -1]

procesar_matriz(A1, [b1_3, b2_3, b3_3], "A1")



==================== A1 ====================
[01-13 18:28:47][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 18:28:47][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 18:28:47][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 18:28:47][INFO] Sustitución hacia adelante
[01-13 18:28:47][INFO] y = 
[[ 1.]
 [-2.]
 [ 0.]]
[01-13 18:28:47][INFO] Sustitución hacia atrás
[01-13 18:28:47][INFO] i = 1
[01-13 18:28:47][INFO] suma = [0.]
[01-13 18:28:47][INFO] U[i, i] = -5.0


[01-13 18:28:47][INFO] y[i] = [-2.]
[01-13 18:28:47][INFO] i = 0
[01-13 18:28:47][INFO] suma = [1.2]
[01-13 18:28:47][INFO] U[i, i] = 1.0
[01-13 18:28:47][INFO] y[i] = [1.]
[01-13 18:28:48][INFO] Sustitución hacia adelante
[01-13 18:28:48][INFO] y = 
[[ 0.]
 [ 1.]
 [-2.]]
[01-13 18:28:48][INFO] Sustitución hacia atrás
[01-13 18:28:48][INFO] i = 1
[01-13 18:28:48][INFO] suma = [-2.]
[01-13 18:28:48][INFO] U[i, i] = -5.0
[01-13 18:28:48][INFO] y[i] = [1.]
[01-13 18:28:48][INFO] i = 0
[01-13 18:28:48][INFO] suma = [-0.2]
[01-13 18:28:48][INFO] U[i, i] = 1.0
[01-13 18:28:48][INFO] y[i] = [0.]
[01-13 18:28:48][INFO] Sustitución hacia adelante
[01-13 18:28:48][INFO] y = 
[[0.]
 [0.]
 [1.]]
[01-13 18:28:48][INFO] Sustitución hacia atrás
[01-13 18:28:48][INFO] i = 1
[01-13 18:28:48][INFO] suma = [1.]
[01-13 18:28:48][INFO] U[i, i] = -5.0
[01-13 18:28:48][INFO] y[i] = [0.]
[01-13 18:28:48][INFO] i = 0
[01-13 18:28:48][INFO] suma = [-0.2]
[01-13 18:28:48][INFO] U[i, i] = 1.0
[01-13 18:28:48][INF

# Ejercicio 2

In [9]:

A2 = [
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0],
]

b1_3 = [1, 2, 4]
b2_3 = [3, -5, 2]
b3_3 = [7, 8, -1]

procesar_matriz(A2, [b1_3, b2_3, b3_3], "A2")



==================== A2 ====================
[01-13 18:29:20][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 18:29:20][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 18:29:20][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 18:29:20][INFO] Sustitución hacia adelante
[01-13 18:29:20][INFO] y = 
[[ 1.]
 [ 0.]
 [-5.]]
[01-13 18:29:20][INFO] Sustitución hacia atrás
[01-13 18:29:20][INFO] i = 1
[01-13 18:29:20][INFO] suma = [-20.]
[01-13 18:29:20][INFO] U[i, i] = 1.0
[01-13 18:29:20][INFO] y[i] = [0.]
[01-13 18:29:20][INFO] i = 0


[01-13 18:29:20][INFO] suma = [25.]
[01-13 18:29:20][INFO] U[i, i] = 1.0
[01-13 18:29:20][INFO] y[i] = [1.]
[01-13 18:29:20][INFO] Sustitución hacia adelante
[01-13 18:29:20][INFO] y = 
[[0.]
 [1.]
 [4.]]
[01-13 18:29:20][INFO] Sustitución hacia atrás
[01-13 18:29:20][INFO] i = 1
[01-13 18:29:20][INFO] suma = [16.]
[01-13 18:29:20][INFO] U[i, i] = 1.0
[01-13 18:29:20][INFO] y[i] = [1.]
[01-13 18:29:20][INFO] i = 0
[01-13 18:29:20][INFO] suma = [-18.]
[01-13 18:29:20][INFO] U[i, i] = 1.0
[01-13 18:29:20][INFO] y[i] = [0.]
[01-13 18:29:20][INFO] Sustitución hacia adelante
[01-13 18:29:20][INFO] y = 
[[0.]
 [0.]
 [1.]]
[01-13 18:29:20][INFO] Sustitución hacia atrás
[01-13 18:29:20][INFO] i = 1
[01-13 18:29:20][INFO] suma = [4.]
[01-13 18:29:20][INFO] U[i, i] = 1.0
[01-13 18:29:20][INFO] y[i] = [0.]
[01-13 18:29:20][INFO] i = 0
[01-13 18:29:20][INFO] suma = [-5.]
[01-13 18:29:20][INFO] U[i, i] = 1.0
[01-13 18:29:20][INFO] y[i] = [0.]

Inversa de A2:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -

In [10]:

A3 = [
    [4, 2, 1],
    [2, 1, 3],
    [1, 3, 4],
]

b1_3 = [1, 2, 4]
b2_3 = [3, -5, 2]
b3_3 = [7, 8, -1]

procesar_matriz(A3, [b1_3, b2_3, b3_3], "A3")



==================== A3 ====================
[01-13 18:29:39][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

In [11]:

A4 = [
    [2, 4, 6, 1],
    [4, 7, 5, -6],
    [2, 5, 18, 10],
    [6, 12, 38, 16],
]

b1_4 = [1, 2, 4, 5]
b2_4 = [3, -5, 2, 6]
b3_4 = [7, 8, -1, 0]

procesar_matriz(A4, [b1_4, b2_4, b3_4], "A4")



==================== A4 ====================
[01-13 18:30:06][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 18:30:06][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 18:30:06][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 18:30:06][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 18:30:06][INFO] Sustitución hacia adelante
[01-13 18:30:06][INFO] y = 
[[ 1.]
 [-2.]
 [-3.]
 [ 9.]]
[01-13 18:30:06][INFO] Sustitución hacia atrás
[01-13 18:30:06][INFO] i = 2
[01-13 18:30:06][INFO] suma = [1.]
[01-13 18:30:06][INFO] U[i, i] = 5.0
[01-13 18:30:06][INFO] y[i] = [-3.]
[01-13 18:30:06][INFO] i = 1
[01-13 18:30:06][INFO] suma = [-2.4]
[01-13 18:30:06][INFO] U[i, i] = -1.0
[01-13 18:30:06][INFO] y[i] = [-2.]
[01-13 18:30:06][INFO] i = 0
[01-13 18:30:06][INFO] suma = [-5.4]
[01-13 18:30:06][INFO] U[i, i] = 2.0
[01-13 18:30:06]